### ISSUE TITLE
Please add the reset function

### ISSUE THREAD

**Issue by marcdelalonde** [aleross/angular-segment-analytics#10]
Hi,
Thank you for your plugin!
Can you please add the reset() function in order to use it when my use logging out ? It would be very useful for anyone I guess!
Thank you in advance

**Comment by aleross** [comment]
Hi @marcdelalonde, `segment.reset()` should already be implemented. You can find it in the list of available methods in [src/config.js](https://github.com/aleross/angular-segment-analytics/blob/master/src/config.js). Is it not working for you?

**Comment by aleross** [comment]
Closing, if this function doesn't work for somebody please comment.
