### ISSUE TITLE
Is it possible to disable/modify default analytics.page() on page load?

### ISSUE THREAD

**Issue by nmartin867** [aleross/angular-segment-analytics#13]
I am attempting to use this module on static pages. Each static page must configure my application angular module. During this configuration I am configuring Segment using segmentProvider. I'm noticing that analytics.page() appears to be called each time a new page is loaded.

Is is possible to disable this?

**Comment by aleross** [comment]
This Angular integration module doesn't call any tracking methods automatically, so you'll want to find the correct functionality in Analytics.js itself. 

There should be a way via the Analytics.js API `.page()` method, or maybe there's another configuration for it: https://segment.com/docs/libraries/analytics.js/#page.
