### ISSUE TITLE
Change "latest" angular dependency to avoid shrinkwrap issues

### ISSUE THREAD

**Issue by robinjoseph08** [aleross/angular-segment-analytics#14]
Hi!

In your [`package.json`](https://github.com/aleross/angular-segment-analytics/blob/0dbcd37f077902f47d15f9e820cc8a64f52d36e8/package.json#L23), you specify the angular dependency with the version of `latest`. Using the `latest` version has proven to be problematic because it doesn't seem like `npm` and the shrinkwrap file can handle resolving the dependencies correctly.

Here are a few issues that explain the issue in a bit more detail:
- https://github.com/npm/npm/issues/13496
- https://github.com/npm/npm/issues/10142

It also might make more sense to make angular a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) instead of a normal dependency. That way, users of your module are required to also have `angular` listed as a dependency, but it doesn't lock down the version as harshly as a normal dependency. You can just specify `1.x.x` or `>= 1.2.0` or whatever minimum requirements you have.

I'd be happy to submit a PR if you let me know how you want to resolve the issue! Thanks for the great work!

**Comment by aleross** [comment]
Thanks for the info @robinjoseph08! Your suggestion of changing it to a peer dependency looks like a good route to go. A PR would be a big help if you have time.
