### ISSUE TITLE
Including module in karma test 

### ISSUE THREAD

**Issue by alecha** [aleross/angular-segment-analytics#2]
Hi, I'm having some issue after I've included this module in my app, this broke my Karma tests.

The error: `'undefined' is not a function (evaluating 'function(a){this.validate(a)}.bind(this)')`

My app runs without issue, so I guess that maybe is something with the karma config, but without this module everything is working fine (tests included). Did you have the same issue?

Thanks.

**Comment by aleross** [comment]
Are you using PhantomJS 1.x as your browser for tests? If so, it doesn't support `Function.prototype.bind`. There are a few polyfills that make it easy to add support, I used `bind-polyfill` installed via bower. I considered removing the calls to `.bind()` just for this reason.

https://github.com/ariya/phantomjs/issues/10522

PhantonJS 2.x supports `Function.prototype.bind()`, but upgrading with Karma isn't straightforward right now.

**Comment by alecha** [comment]
yes I'm using Phantom 1.x, thanks! I'll try the solution linked!

**Comment by aleross** [comment]
Great, let me know if that fixes it. I think I'll also polyfill `.bind()` in the library itself, or remove references to it so that this doesn't happen to others. Thanks for reporting this!

**Comment by dennislo** [comment]
Thanks for mentioning the fix @aleross, since I included this module my karma test started throwing errors 

```
Error: [$injector:modulerr] Failed to instantiate module enterprise due to:
    Error: [$injector:unpr] Unknown provider: segmentProvider
    http://errors.angularjs.org/1.4.8/$injector/unpr?p0=segmentProvider
```

which was caused:
`'undefined' is not a function (evaluating 'function(a){this.validate(a)}.bind(this)')`

I had to do:
1. `bower install bind-polyfill --save`
2. Then  inside my `karma.conf.js` file I add `'bower_components/bind-polyfill/index.js'` in the `files` array. I had to find that out by looking at this exampe https://github.com/aleross/angular-segment-analytics/blob/master/grunt/karma.js

```
module.exports = {
    options: {
        files: [
            'bower_components/bind-polyfill/index.js', // PhantomJS 1.x doesn't support Function.prototype.bind
            'bower_components/angular/angular.js',
            'bower_components/angular-mocks/angular-mocks.js',
            'segment.js',
            'test/*.js',
        ]
...
```

**Comment by aleross** [comment]
I removed the `Function.bind()` calls in the latest version 1.1.9, so if you upgrade you can remove the bind-polyfill.
